import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { HexclaveProvider, HexclaveTheme } from "@hexclave/next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NavBar } from "@/components/nav/nav-bar";
import { hexclaveServerApp } from "@/hexclave/server";
import { Toaster } from "@/components/ui/toast";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <HexclaveProvider app={hexclaveServerApp}>
          <HexclaveTheme>
            <NavBar />
            {children}
            <Toaster timeout={5000} />
          </HexclaveTheme>
        </HexclaveProvider>
      </body>
    </html>
  );
}
